// <auto-generated />
namespace TrashCity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedEmployeemodelandcontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedEmployeemodelandcontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201801050315088_added Employee model and controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
